.*: Assembler messages:
.*:1: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `lwl \$4,0\(\$11\)'
.*:2: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `lwr \$4,3\(\$11\)'
.*:3: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `ldl \$4,0\(\$11\)'
.*:4: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `ldr \$4,7\(\$11\)'
.*:5: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `swl \$4,0\(\$11\)'
.*:6: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `swr \$4,3\(\$11\)'
.*:7: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `sdl \$4,0\(\$11\)'
.*:8: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `sdr \$4,7\(\$11\)'
