.*: Assembler messages:
.*:1: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `lwl'
.*:2: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `lwr'
.*:3: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `ldl'
.*:4: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `ldr'
.*:5: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `swl'
.*:6: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `swr'
.*:7: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `sdl'
.*:8: Error: Unaligned load/store instructions are not allowed with -mocteon-useun `sdr'
