.*\.s: Assembler messages:
.*\.s:5: Error: lui expression \((18446744073709551615|4294967295)\) not in range 0\.\.65535
.*\.s:6: Error: lui expression \(65536\) not in range 0\.\.65535
.*\.s:7: Error: Absolute expression required `lui \$2,\$3'
.*\.s:9: Error: Absolute expression required `lui \$2,0b'
.*\.s:10: Error: Absolute expression required `lui \$2,1f'
.*\.s:12: Error: Absolute expression required `lui \$2,foo'
.*\.s:13: Error: Absolute expression required `lui \$2,bar'
